/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author USER
 */
public class FrmBotGestionar extends javax.swing.JFrame {

    /**
     * Creates new form FrmBotGestionar
     */
    public FrmBotGestionar() {
        initComponents();
        setTitle("BOTICA CRUZ DE MAYO - JAUJA");
        setSize(465, 260);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseGestionar = new javax.swing.JPanel();
        textEncabezado = new javax.swing.JLabel();
        jLabelCajas = new javax.swing.JLabel();
        textCaja = new javax.swing.JTextField();
        jLabelBlisters = new javax.swing.JLabel();
        textBlister = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        textMedicamento = new javax.swing.JLabel();
        jPanelLinea1 = new javax.swing.JPanel();
        jPanelLinea2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseGestionar.setBackground(new java.awt.Color(239, 248, 255));
        jPanelBaseGestionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textEncabezado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textEncabezado.setForeground(new java.awt.Color(0, 0, 51));
        textEncabezado.setText("Número de cajas = Número de blister");
        jPanelBaseGestionar.add(textEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 390, -1));

        jLabelCajas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCajas.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCajas.setText("CAJAS:");
        jPanelBaseGestionar.add(jLabelCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 30));

        textCaja.setBackground(new java.awt.Color(255, 255, 255));
        textCaja.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textCaja.setForeground(new java.awt.Color(0, 0, 0));
        textCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCaja.setBorder(null);
        textCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseGestionar.add(textCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, 30));

        jLabelBlisters.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelBlisters.setForeground(new java.awt.Color(0, 0, 51));
        jLabelBlisters.setText("BLISTERS:");
        jPanelBaseGestionar.add(jLabelBlisters, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 30));

        textBlister.setBackground(new java.awt.Color(255, 255, 255));
        textBlister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textBlister.setForeground(new java.awt.Color(0, 0, 0));
        textBlister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBlister.setBorder(null);
        textBlister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseGestionar.add(textBlister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 30));

        btnAceptar.setText("ACEPTAR");
        jPanelBaseGestionar.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        textMedicamento.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textMedicamento.setForeground(new java.awt.Color(0, 0, 51));
        textMedicamento.setText("Medicamento");
        jPanelBaseGestionar.add(textMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 390, -1));

        jPanelLinea1.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea1Layout = new javax.swing.GroupLayout(jPanelLinea1);
        jPanelLinea1.setLayout(jPanelLinea1Layout);
        jPanelLinea1Layout.setHorizontalGroup(
            jPanelLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanelLinea1Layout.setVerticalGroup(
            jPanelLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBaseGestionar.add(jPanelLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, 3));

        jPanelLinea2.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea2Layout = new javax.swing.GroupLayout(jPanelLinea2);
        jPanelLinea2.setLayout(jPanelLinea2Layout);
        jPanelLinea2Layout.setHorizontalGroup(
            jPanelLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanelLinea2Layout.setVerticalGroup(
            jPanelLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBaseGestionar.add(jPanelLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBotGestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBotGestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBotGestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBotGestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBotGestionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabelBlisters;
    private javax.swing.JLabel jLabelCajas;
    private javax.swing.JPanel jPanelBaseGestionar;
    private javax.swing.JPanel jPanelLinea1;
    private javax.swing.JPanel jPanelLinea2;
    public javax.swing.JTextField textBlister;
    public javax.swing.JTextField textCaja;
    public javax.swing.JLabel textEncabezado;
    public javax.swing.JLabel textMedicamento;
    // End of variables declaration//GEN-END:variables
}
