/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmBuscarOrdenCompra extends javax.swing.JFrame {
    
    public static DefaultTableModel modelCompra;

    /**
     * Creates new form FrmBuscarOrdenCompra
     */
    public FrmBuscarOrdenCompra() {
        initComponents();
        setTitle("BOTICA CRUZ DE MAYO - JAUJA");
        setSize(1193, 660);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseBusOrdenCompra = new javax.swing.JPanel();
        jPanelRetPrincipal2 = new javax.swing.JPanel();
        jLabelBusOrdenCompra = new javax.swing.JLabel();
        jLabelNomProveedor = new javax.swing.JLabel();
        jButtonBusOrdenCompra = new javax.swing.JButton();
        jScrollPaneBusOrdCompra = new javax.swing.JScrollPane();
        jTableBusOrdCompra = new javax.swing.JTable();
        jbtnDetalle = new javax.swing.JButton();
        jcbProveedores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseBusOrdenCompra.setBackground(new java.awt.Color(228, 241, 254));
        jPanelBaseBusOrdenCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRetPrincipal2.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRetPrincipal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRetPrincipal2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRetPrincipal2Layout = new javax.swing.GroupLayout(jPanelRetPrincipal2);
        jPanelRetPrincipal2.setLayout(jPanelRetPrincipal2Layout);
        jPanelRetPrincipal2Layout.setHorizontalGroup(
            jPanelRetPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelRetPrincipal2Layout.setVerticalGroup(
            jPanelRetPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelBaseBusOrdenCompra.add(jPanelRetPrincipal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, 50, 40));

        jLabelBusOrdenCompra.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelBusOrdenCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelBusOrdenCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusOrdenCompra.setText("BUSCAR ORDEN DE COMPRA");
        jPanelBaseBusOrdenCompra.add(jLabelBusOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 410, -1));

        jLabelNomProveedor.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelNomProveedor.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNomProveedor.setText("NOMBRE DEL PROVEEDOR:");
        jPanelBaseBusOrdenCompra.add(jLabelNomProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 260, -1));

        jButtonBusOrdenCompra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonBusOrdenCompra.setText("BUSCAR");
        jPanelBaseBusOrdenCompra.add(jButtonBusOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 110, 40));

        jTableBusOrdCompra.setBackground(new java.awt.Color(0, 0, 38));
        jTableBusOrdCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTableBusOrdCompra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTableBusOrdCompra.setForeground(new java.awt.Color(255, 255, 255));
        jTableBusOrdCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° ORDEN", "FECHA COMPRA", "FECHA ENTREGA", "RUC PROVEEDOR", "COSTO TOTAL", "DETALLE", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBusOrdCompra.setRowHeight(30);
        jTableBusOrdCompra.setSelectionBackground(new java.awt.Color(228, 241, 254));
        jTableBusOrdCompra.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPaneBusOrdCompra.setViewportView(jTableBusOrdCompra);

        jPanelBaseBusOrdenCompra.add(jScrollPaneBusOrdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 1070, 320));

        jbtnDetalle.setText("VER DETALLE");
        jbtnDetalle.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelBaseBusOrdenCompra.add(jbtnDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, -1, -1));

        jPanelBaseBusOrdenCompra.add(jcbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseBusOrdenCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseBusOrdenCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRetPrincipal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRetPrincipal2MouseClicked
        FrmPrincipal ret1 = new FrmPrincipal();
        ret1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelRetPrincipal2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarOrdenCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBusOrdenCompra;
    private javax.swing.JLabel jLabelBusOrdenCompra;
    private javax.swing.JLabel jLabelNomProveedor;
    private javax.swing.JPanel jPanelBaseBusOrdenCompra;
    public javax.swing.JPanel jPanelRetPrincipal2;
    public javax.swing.JScrollPane jScrollPaneBusOrdCompra;
    public javax.swing.JTable jTableBusOrdCompra;
    public javax.swing.JButton jbtnDetalle;
    public javax.swing.JComboBox<String> jcbProveedores;
    // End of variables declaration//GEN-END:variables
}
