/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author USER
 */
public class FrmGestionarInventario extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionarInventario
     */
    public FrmGestionarInventario() {
        initComponents();
        setTitle("BOTICA CRUZ DE MAYO - JAUJA");
        setSize(1000, 670);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseGestionInventario = new javax.swing.JPanel();
        jLabelRegDatProducto = new javax.swing.JLabel();
        jLabelNumOrdenCompra = new javax.swing.JLabel();
        jTextFieldNumOrdenCompra = new javax.swing.JTextField();
        jLabelProveedor = new javax.swing.JLabel();
        jTextFieldProveedor = new javax.swing.JTextField();
        jScrollPaneBusProducto = new javax.swing.JScrollPane();
        jTableGesItnventario = new javax.swing.JTable();
        jPanelRetPrincipal8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseGestionInventario.setBackground(new java.awt.Color(228, 241, 254));
        jPanelBaseGestionInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegDatProducto.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelRegDatProducto.setForeground(new java.awt.Color(0, 0, 51));
        jLabelRegDatProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegDatProducto.setText("GESTIONAR INVENTARIO");
        jPanelBaseGestionInventario.add(jLabelRegDatProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 390, -1));

        jLabelNumOrdenCompra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNumOrdenCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNumOrdenCompra.setText("N° ORDEN COMPRA:");
        jPanelBaseGestionInventario.add(jLabelNumOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, -1));

        jTextFieldNumOrdenCompra.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldNumOrdenCompra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldNumOrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNumOrdenCompra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNumOrdenCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseGestionInventario.add(jTextFieldNumOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 320, 40));

        jLabelProveedor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelProveedor.setForeground(new java.awt.Color(0, 0, 51));
        jLabelProveedor.setText("PROVEEDOR:");
        jPanelBaseGestionInventario.add(jLabelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, -1));

        jTextFieldProveedor.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldProveedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseGestionInventario.add(jTextFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 320, 40));

        jTableGesItnventario.setBackground(new java.awt.Color(0, 0, 38));
        jTableGesItnventario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTableGesItnventario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTableGesItnventario.setForeground(new java.awt.Color(255, 255, 255));
        jTableGesItnventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "GESTIONAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGesItnventario.setRowHeight(30);
        jTableGesItnventario.setSelectionBackground(new java.awt.Color(228, 241, 254));
        jTableGesItnventario.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPaneBusProducto.setViewportView(jTableGesItnventario);

        jPanelBaseGestionInventario.add(jScrollPaneBusProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 890, 240));

        jPanelRetPrincipal8.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRetPrincipal8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRetPrincipal8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRetPrincipal8Layout = new javax.swing.GroupLayout(jPanelRetPrincipal8);
        jPanelRetPrincipal8.setLayout(jPanelRetPrincipal8Layout);
        jPanelRetPrincipal8Layout.setHorizontalGroup(
            jPanelRetPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelRetPrincipal8Layout.setVerticalGroup(
            jPanelRetPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelBaseGestionInventario.add(jPanelRetPrincipal8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseGestionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseGestionInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRetPrincipal8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRetPrincipal8MouseClicked
//        FrmRegistrarGuiaRemision ret8 = new FrmRegistrarGuiaRemision();
//        ret8.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jPanelRetPrincipal8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNumOrdenCompra;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelRegDatProducto;
    private javax.swing.JPanel jPanelBaseGestionInventario;
    private javax.swing.JPanel jPanelRetPrincipal8;
    public javax.swing.JScrollPane jScrollPaneBusProducto;
    public javax.swing.JTable jTableGesItnventario;
    public javax.swing.JTextField jTextFieldNumOrdenCompra;
    public javax.swing.JTextField jTextFieldProveedor;
    // End of variables declaration//GEN-END:variables
}
