package vista;

import conexion.Conexion;

import javax.swing.JOptionPane;

/**
 *
 * @author André Mujica
 */
public class FrmLogin extends javax.swing.JFrame {

    public FrmLogin() {
        initComponents();
        
        setTitle("BOTICA CRUZ DE MAYO - JAUJA");

        setSize(1128, 658);
        setResizable(false);       
        setLocationRelativeTo(null);
       
        Conexion.getInstance();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelFranjaDerecha = new javax.swing.JPanel();
        jPanelLinea2 = new javax.swing.JPanel();
        jPanelLinea1 = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jLabelNomBotica = new javax.swing.JLabel();
        jLabelNomContraseña = new javax.swing.JLabel();
        jLabelNomUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jPanelBotonIngresar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPanelFranja1 = new javax.swing.JPanel();
        jPanelInferior = new javax.swing.JPanel();
        jLabelFondoCeleste = new javax.swing.JLabel();
        jLabelFondoImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBase.setBackground(new java.awt.Color(228, 241, 254));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFranjaDerecha.setBackground(new java.awt.Color(23, 178, 178));

        javax.swing.GroupLayout jPanelFranjaDerechaLayout = new javax.swing.GroupLayout(jPanelFranjaDerecha);
        jPanelFranjaDerecha.setLayout(jPanelFranjaDerechaLayout);
        jPanelFranjaDerechaLayout.setHorizontalGroup(
            jPanelFranjaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanelFranjaDerechaLayout.setVerticalGroup(
            jPanelFranjaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelFranjaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 0, 4, 630));

        jPanelLinea2.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea2Layout = new javax.swing.GroupLayout(jPanelLinea2);
        jPanelLinea2.setLayout(jPanelLinea2Layout);
        jPanelLinea2Layout.setHorizontalGroup(
            jPanelLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanelLinea2Layout.setVerticalGroup(
            jPanelLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 330, 3));

        jPanelLinea1.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea1Layout = new javax.swing.GroupLayout(jPanelLinea1);
        jPanelLinea1.setLayout(jPanelLinea1Layout);
        jPanelLinea1Layout.setHorizontalGroup(
            jPanelLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanelLinea1Layout.setVerticalGroup(
            jPanelLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 330, 3));

        jPanelCentral.setBackground(new java.awt.Color(228, 241, 254));
        jPanelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomBotica.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNomBotica.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabelNomBotica.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomBotica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomBotica.setText("CRUZ DE MAYO");
        jPanelCentral.add(jLabelNomBotica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 40));

        jLabelNomContraseña.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelNomContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomContraseña.setText("CONTRASEÑA:");
        jPanelCentral.add(jLabelNomContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 160, 30));

        jLabelNomUsuario.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelNomUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomUsuario.setText("USUARIO:");
        jPanelCentral.add(jLabelNomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 30));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuario.setToolTipText("");
        jTextFieldUsuario.setBorder(null);
        jPanelCentral.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 290, 40));

        jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraseña.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPasswordFieldContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldContraseña.setToolTipText("");
        jPasswordFieldContraseña.setBorder(null);
        jPanelCentral.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 290, 40));

        jPanelBotonIngresar.setBackground(new java.awt.Color(0, 5, 25));
        jPanelBotonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBotonIngresarMouseClicked(evt);
            }
        });
        jPanelBotonIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESAR");
        jPanelBotonIngresar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 142, 28));

        jPanelCentral.add(jPanelBotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 180, 40));

        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelCentral.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 175, 50, 50));

        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelCentral.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 303, 40, 50));

        jPanelBase.add(jPanelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 430, 490));

        jPanelFranja1.setBackground(new java.awt.Color(23, 178, 178));

        javax.swing.GroupLayout jPanelFranja1Layout = new javax.swing.GroupLayout(jPanelFranja1);
        jPanelFranja1.setLayout(jPanelFranja1Layout);
        jPanelFranja1Layout.setHorizontalGroup(
            jPanelFranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanelFranja1Layout.setVerticalGroup(
            jPanelFranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelFranja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1115, 3));

        jPanelInferior.setBackground(new java.awt.Color(0, 5, 25));
        jPanelInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInferiorMouseClicked(evt);
            }
        });
        jPanelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBase.add(jPanelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1115, 140));

        jLabelFondoCeleste.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Dropbox\\Mi PC (LAPTOP-ML2VI351)\\Documents\\CICLOS UNMSM\\CICLO VI\\DISEÑO DE SISTEMAS DE INFORMACIÓN\\ProyectoFinal\\SistemaBotica\\ProyectoDSI2.0\\ProyectoFinalDSI\\src\\main\\java\\imagenes\\celeste.png")); // NOI18N
        jPanelBase.add(jLabelFondoCeleste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 630));

        jLabelFondoImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Dropbox\\Mi PC (LAPTOP-ML2VI351)\\Documents\\CICLOS UNMSM\\CICLO VI\\DISEÑO DE SISTEMAS DE INFORMACIÓN\\ProyectoFinal\\SistemaBotica\\ProyectoDSI2.0\\ProyectoFinalDSI\\src\\main\\java\\imagenes\\Farmaceutico.jpg")); // NOI18N
        jPanelBase.add(jLabelFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelBotonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBotonIngresarMouseClicked
//        String usuario = "POR DEFINIR";
//        String contraseña = "POR DEFINIR";
//        
//        String Pass = new String(jPasswordFieldContraseña.getPassword());
//        
//        if(jTextFieldUsuario.getText().equals(usuario)&& Pass.equals(contra)){
            FrmPrincipal principal = new FrmPrincipal(); 
            principal.setVisible(true); 
            dispose(); 
//        }
//        else{
//            
//            JOptionPane.showMessageDialog(this, "Usuario / Contraseña incorrecta"); 
//        }
    }//GEN-LAST:event_jPanelBotonIngresarMouseClicked

    private void jPanelInferiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInferiorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelInferiorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondoCeleste;
    private javax.swing.JLabel jLabelFondoImagen;
    private javax.swing.JLabel jLabelNomBotica;
    private javax.swing.JLabel jLabelNomContraseña;
    private javax.swing.JLabel jLabelNomUsuario;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelBase;
    public javax.swing.JPanel jPanelBotonIngresar;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelFranja1;
    private javax.swing.JPanel jPanelFranjaDerecha;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelLinea1;
    private javax.swing.JPanel jPanelLinea2;
    public javax.swing.JPasswordField jPasswordFieldContraseña;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
