/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmRegistrarOrdenCompra extends javax.swing.JFrame {
    
    public static DefaultTableModel modelCompra; 

    /**
     * Creates new form RegistrarOrdenCompra
     */
    public FrmRegistrarOrdenCompra() {
        initComponents();
//        setTitle("BOTICA CRUZ DE MAYO - JAUJA");
//        setSize(990, 660);
//        setResizable(false);
//        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseRegOrdenCompra = new javax.swing.JPanel();
        jPanelRetPrincipal6 = new javax.swing.JPanel();
        jLabelRegOrdenCompra = new javax.swing.JLabel();
        jLabelPrecioCompra = new javax.swing.JLabel();
        jTextFieldPrecCompra = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jLabelCodProducto = new javax.swing.JLabel();
        jTextFieldCodProducto = new javax.swing.JTextField();
        jLabelEmpresa = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        JComboProveedor = new javax.swing.JComboBox<>();
        jScrollPaneRegOrdCompra = new javax.swing.JScrollPane();
        jTableOrdCompra = new javax.swing.JTable();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jbtnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseRegOrdenCompra.setBackground(new java.awt.Color(228, 241, 254));
        jPanelBaseRegOrdenCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRetPrincipal6.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRetPrincipal6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRetPrincipal6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRetPrincipal6Layout = new javax.swing.GroupLayout(jPanelRetPrincipal6);
        jPanelRetPrincipal6.setLayout(jPanelRetPrincipal6Layout);
        jPanelRetPrincipal6Layout.setHorizontalGroup(
            jPanelRetPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelRetPrincipal6Layout.setVerticalGroup(
            jPanelRetPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelBaseRegOrdenCompra.add(jPanelRetPrincipal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, 40, 40));

        jLabelRegOrdenCompra.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelRegOrdenCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelRegOrdenCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegOrdenCompra.setText("REGISTRAR ORDEN DE COMPRA");
        jPanelBaseRegOrdenCompra.add(jLabelRegOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 470, -1));

        jLabelPrecioCompra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelPrecioCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelPrecioCompra.setText("PRECIO COMPRA:");
        jPanelBaseRegOrdenCompra.add(jLabelPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, -1));

        jTextFieldPrecCompra.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldPrecCompra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldPrecCompra.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldPrecCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecCompraActionPerformed(evt);
            }
        });
        jPanelBaseRegOrdenCompra.add(jTextFieldPrecCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 40));

        jbtnGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbtnGuardar.setText("GUARDAR");
        jPanelBaseRegOrdenCompra.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 110, 40));

        jLabelCodProducto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCodProducto.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCodProducto.setText("CÓDIGO MEDICAMENTO:");
        jPanelBaseRegOrdenCompra.add(jLabelCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 210, -1));

        jTextFieldCodProducto.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldCodProducto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldCodProducto.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCodProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelBaseRegOrdenCompra.add(jTextFieldCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 160, 40));

        jLabelEmpresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(0, 0, 51));
        jLabelEmpresa.setText("PROVEEDOR:");
        jPanelBaseRegOrdenCompra.add(jLabelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, -1));

        jTextFieldCantidad.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldCantidad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanelBaseRegOrdenCompra.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 120, 40));

        jLabelCantidad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCantidad.setText("CANTIDAD:");
        jPanelBaseRegOrdenCompra.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 120, -1));

        JComboProveedor.setBackground(new java.awt.Color(0, 0, 38));
        JComboProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        JComboProveedor.setForeground(new java.awt.Color(255, 255, 255));
        JComboProveedor.setAutoscrolls(true);
        JComboProveedor.setBorder(null);
        JComboProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JComboProveedor.setName(""); // NOI18N
        JComboProveedor.setOpaque(false);
        jPanelBaseRegOrdenCompra.add(JComboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 440, 40));

        jTableOrdCompra.setBackground(new java.awt.Color(0, 0, 38));
        jTableOrdCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTableOrdCompra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTableOrdCompra.setForeground(new java.awt.Color(255, 255, 255));
        jTableOrdCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableOrdCompra.setRowHeight(30);
        jTableOrdCompra.setSelectionBackground(new java.awt.Color(228, 241, 254));
        jTableOrdCompra.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPaneRegOrdCompra.setViewportView(jTableOrdCompra);

        jPanelBaseRegOrdenCompra.add(jScrollPaneRegOrdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 720, 240));

        jLabelTotal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTotal.setText("TOTAL:");
        jPanelBaseRegOrdenCompra.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 70, -1));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTotal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        jPanelBaseRegOrdenCompra.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 190, 40));

        jbtnAgregar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbtnAgregar.setText("AGREGAR");
        jPanelBaseRegOrdenCompra.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBaseRegOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBaseRegOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRetPrincipal6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRetPrincipal6MouseClicked
//        FrmPrincipal ret6 = new FrmPrincipal();
//        ret6.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jPanelRetPrincipal6MouseClicked

    private void jTextFieldPrecCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecCompraActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarOrdenCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JComboProveedor;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodProducto;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelPrecioCompra;
    private javax.swing.JLabel jLabelRegOrdenCompra;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelBaseRegOrdenCompra;
    public javax.swing.JPanel jPanelRetPrincipal6;
    public javax.swing.JScrollPane jScrollPaneRegOrdCompra;
    public javax.swing.JTable jTableOrdCompra;
    public javax.swing.JTextField jTextFieldCantidad;
    public javax.swing.JTextField jTextFieldCodProducto;
    public javax.swing.JTextField jTextFieldPrecCompra;
    public javax.swing.JTextField jTextFieldTotal;
    public javax.swing.JButton jbtnAgregar;
    public javax.swing.JButton jbtnGuardar;
    // End of variables declaration//GEN-END:variables
}
