/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.UIManager;


/**
 *
 * @author USER
 */
public class FrmRegistrarGuiaRemision extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarGuiaRemision
     */
    public FrmRegistrarGuiaRemision() {
        initComponents();
        setTitle("BOTICA CRUZ DE MAYO - JAUJA");
        setSize(1068, 569);
        setResizable(false);
        setLocationRelativeTo(null);
        exploradorColor();
        
    }
    
    public void exploradorColor(){//para color formato Windows10
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseRegGuiaRemision = new javax.swing.JPanel();
        jPanelRetPrincipal5 = new javax.swing.JPanel();
        jLabelRegGuiaRemision = new javax.swing.JLabel();
        jLabelNumOrdCompra = new javax.swing.JLabel();
        jTextFieldNumOrdCompra = new javax.swing.JTextField();
        jButtonSubirGuiaRemision = new javax.swing.JButton();
        jLabelProveedor = new javax.swing.JLabel();
        jTextFieldPunPartida = new javax.swing.JTextField();
        jLabelPunPartida = new javax.swing.JLabel();
        JComboBoxProveedor = new javax.swing.JComboBox<>();
        jLabelNombreArchivo = new javax.swing.JLabel();
        jTextFieldNumGuiaRemision = new javax.swing.JTextField();
        jLabelMotTraslado = new javax.swing.JLabel();
        jTextFieldMotTraslado = new javax.swing.JTextField();
        jLabelFechaIniTraslado = new javax.swing.JLabel();
        jTextFieldFechaIniTraslado = new javax.swing.JTextField();
        jButtonBusGuiaRemision = new javax.swing.JButton();
        jPanelGuiaRemision = new javax.swing.JPanel();
        jButtonGuardarGuiaRemision = new javax.swing.JButton();
        JTestFieldNomArchivo = new javax.swing.JTextField();
        jLabelNumGuiaRemision = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseRegGuiaRemision.setBackground(new java.awt.Color(228, 241, 254));
        jPanelBaseRegGuiaRemision.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRetPrincipal5.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRetPrincipal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRetPrincipal5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRetPrincipal5Layout = new javax.swing.GroupLayout(jPanelRetPrincipal5);
        jPanelRetPrincipal5.setLayout(jPanelRetPrincipal5Layout);
        jPanelRetPrincipal5Layout.setHorizontalGroup(
            jPanelRetPrincipal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelRetPrincipal5Layout.setVerticalGroup(
            jPanelRetPrincipal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelBaseRegGuiaRemision.add(jPanelRetPrincipal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 60, 60));

        jLabelRegGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelRegGuiaRemision.setForeground(new java.awt.Color(0, 0, 51));
        jLabelRegGuiaRemision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegGuiaRemision.setText("REGISTRAR GUÍA DE REMISIÓN");
        jPanelBaseRegGuiaRemision.add(jLabelRegGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 440, -1));

        jLabelNumOrdCompra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNumOrdCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNumOrdCompra.setText("N° ORDEN COMPRA");
        jPanelBaseRegGuiaRemision.add(jLabelNumOrdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 260, -1));

        jTextFieldNumOrdCompra.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldNumOrdCompra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldNumOrdCompra.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNumOrdCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(jTextFieldNumOrdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 40));

        jButtonSubirGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonSubirGuiaRemision.setText("SUBIR GUÍA REMISIÓN");
        jButtonSubirGuiaRemision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirGuiaRemisionActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(jButtonSubirGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 330, 40));

        jLabelProveedor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelProveedor.setForeground(new java.awt.Color(0, 0, 51));
        jLabelProveedor.setText("PROVEEDOR");
        jPanelBaseRegGuiaRemision.add(jLabelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 260, -1));

        jTextFieldPunPartida.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldPunPartida.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldPunPartida.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPunPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(jTextFieldPunPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 180, 40));

        jLabelPunPartida.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelPunPartida.setForeground(new java.awt.Color(0, 0, 51));
        jLabelPunPartida.setText("PUNTO PARTIDA");
        jPanelBaseRegGuiaRemision.add(jLabelPunPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, -1));

        JComboBoxProveedor.setBackground(new java.awt.Color(0, 0, 38));
        JComboBoxProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        JComboBoxProveedor.setForeground(new java.awt.Color(0, 0, 0));
        JComboBoxProveedor.setAutoscrolls(true);
        JComboBoxProveedor.setBorder(null);
        JComboBoxProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JComboBoxProveedor.setName(""); // NOI18N
        JComboBoxProveedor.setOpaque(false);
        jPanelBaseRegGuiaRemision.add(JComboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, 40));

        jLabelNombreArchivo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNombreArchivo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNombreArchivo.setText("NOMBRE:");
        jPanelBaseRegGuiaRemision.add(jLabelNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 88, 80, 30));

        jTextFieldNumGuiaRemision.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldNumGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldNumGuiaRemision.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNumGuiaRemision.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(jTextFieldNumGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 180, 40));

        jLabelMotTraslado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelMotTraslado.setForeground(new java.awt.Color(0, 0, 51));
        jLabelMotTraslado.setText("MOTIVO TRASLADO");
        jPanelBaseRegGuiaRemision.add(jLabelMotTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, -1));

        jTextFieldMotTraslado.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldMotTraslado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldMotTraslado.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldMotTraslado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(jTextFieldMotTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 320, 40));

        jLabelFechaIniTraslado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelFechaIniTraslado.setForeground(new java.awt.Color(0, 0, 51));
        jLabelFechaIniTraslado.setText("FECHA INICIO TRASLADO");
        jPanelBaseRegGuiaRemision.add(jLabelFechaIniTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 240, -1));

        jTextFieldFechaIniTraslado.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldFechaIniTraslado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldFechaIniTraslado.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaIniTraslado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(jTextFieldFechaIniTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 180, 40));

        jButtonBusGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonBusGuiaRemision.setText("BUSCAR");
        jButtonBusGuiaRemision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusGuiaRemisionActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(jButtonBusGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 40));

        javax.swing.GroupLayout jPanelGuiaRemisionLayout = new javax.swing.GroupLayout(jPanelGuiaRemision);
        jPanelGuiaRemision.setLayout(jPanelGuiaRemisionLayout);
        jPanelGuiaRemisionLayout.setHorizontalGroup(
            jPanelGuiaRemisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanelGuiaRemisionLayout.setVerticalGroup(
            jPanelGuiaRemisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanelBaseRegGuiaRemision.add(jPanelGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 330, 240));

        jButtonGuardarGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonGuardarGuiaRemision.setText("GUARDAR");
        jButtonGuardarGuiaRemision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarGuiaRemisionMouseClicked(evt);
            }
        });
        jButtonGuardarGuiaRemision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarGuiaRemisionActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(jButtonGuardarGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 110, 40));

        JTestFieldNomArchivo.setEditable(false);
        JTestFieldNomArchivo.setBackground(new java.awt.Color(0, 0, 38));
        JTestFieldNomArchivo.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        JTestFieldNomArchivo.setForeground(new java.awt.Color(255, 255, 255));
        JTestFieldNomArchivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTestFieldNomArchivo.setBorder(null);
        JTestFieldNomArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTestFieldNomArchivoActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(JTestFieldNomArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 240, 40));

        jLabelNumGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNumGuiaRemision.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNumGuiaRemision.setText("N° GUÍA REMISIÓN");
        jPanelBaseRegGuiaRemision.add(jLabelNumGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseRegGuiaRemision, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseRegGuiaRemision, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRetPrincipal5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRetPrincipal5MouseClicked
        FrmPrincipal ret5 = new FrmPrincipal();
        ret5.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelRetPrincipal5MouseClicked

    private void jButtonSubirGuiaRemisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirGuiaRemisionActionPerformed
        
    }//GEN-LAST:event_jButtonSubirGuiaRemisionActionPerformed

    private void jButtonBusGuiaRemisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusGuiaRemisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBusGuiaRemisionActionPerformed

    private void jButtonGuardarGuiaRemisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarGuiaRemisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarGuiaRemisionActionPerformed

    private void JTestFieldNomArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTestFieldNomArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTestFieldNomArchivoActionPerformed

    private void jButtonGuardarGuiaRemisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarGuiaRemisionMouseClicked
        FrmGestionarInventario guardar = new FrmGestionarInventario();
        guardar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGuardarGuiaRemisionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarGuiaRemision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JComboBoxProveedor;
    public javax.swing.JTextField JTestFieldNomArchivo;
    private javax.swing.JButton jButtonBusGuiaRemision;
    private javax.swing.JButton jButtonGuardarGuiaRemision;
    private javax.swing.JButton jButtonSubirGuiaRemision;
    private javax.swing.JLabel jLabelFechaIniTraslado;
    private javax.swing.JLabel jLabelMotTraslado;
    private javax.swing.JLabel jLabelNombreArchivo;
    private javax.swing.JLabel jLabelNumGuiaRemision;
    private javax.swing.JLabel jLabelNumOrdCompra;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelPunPartida;
    private javax.swing.JLabel jLabelRegGuiaRemision;
    private javax.swing.JPanel jPanelBaseRegGuiaRemision;
    private javax.swing.JPanel jPanelGuiaRemision;
    private javax.swing.JPanel jPanelRetPrincipal5;
    public javax.swing.JTextField jTextFieldFechaIniTraslado;
    public javax.swing.JTextField jTextFieldMotTraslado;
    public javax.swing.JTextField jTextFieldNumGuiaRemision;
    public javax.swing.JTextField jTextFieldNumOrdCompra;
    public javax.swing.JTextField jTextFieldPunPartida;
    // End of variables declaration//GEN-END:variables
}
