/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.UIManager;


/**
 *
 * @author USER
 */
public class FrmRegistrarGuiaRemision extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarGuiaRemision
     */
    public FrmRegistrarGuiaRemision() {
        initComponents();
        setTitle("BOTICA CRUZ DE MAYO - JAUJA");
        setSize(1068, 569);
        setResizable(false);
        setLocationRelativeTo(null);
        exploradorColor();
        
    }
    
    public void exploradorColor(){//para color formato Windows10
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseRegGuiaRemision = new javax.swing.JPanel();
        jPanelRetPrincipal5 = new javax.swing.JPanel();
        jLabelRegGuiaRemision = new javax.swing.JLabel();
        jLabelNumOrdCompra = new javax.swing.JLabel();
        textOrden = new javax.swing.JTextField();
        botonArchivo = new javax.swing.JButton();
        jLabelProveedor = new javax.swing.JLabel();
        textPartida = new javax.swing.JTextField();
        jLabelPunPartida = new javax.swing.JLabel();
        jLabelNombreArchivo = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        jLabelMotTraslado = new javax.swing.JLabel();
        textProveedor = new javax.swing.JTextField();
        jLabelFechaIniTraslado = new javax.swing.JLabel();
        textAnio = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        panelArchivo = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        textArchivo = new javax.swing.JTextField();
        jLabelNumGuiaRemision = new javax.swing.JLabel();
        textMotivo = new javax.swing.JTextField();
        textDia = new javax.swing.JTextField();
        textMes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseRegGuiaRemision.setBackground(new java.awt.Color(228, 241, 254));
        jPanelBaseRegGuiaRemision.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRetPrincipal5.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRetPrincipal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRetPrincipal5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRetPrincipal5Layout = new javax.swing.GroupLayout(jPanelRetPrincipal5);
        jPanelRetPrincipal5.setLayout(jPanelRetPrincipal5Layout);
        jPanelRetPrincipal5Layout.setHorizontalGroup(
            jPanelRetPrincipal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelRetPrincipal5Layout.setVerticalGroup(
            jPanelRetPrincipal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelBaseRegGuiaRemision.add(jPanelRetPrincipal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 60, 60));

        jLabelRegGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelRegGuiaRemision.setForeground(new java.awt.Color(0, 0, 51));
        jLabelRegGuiaRemision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegGuiaRemision.setText("REGISTRAR GUÍA DE REMISIÓN");
        jPanelBaseRegGuiaRemision.add(jLabelRegGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 440, -1));

        jLabelNumOrdCompra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNumOrdCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNumOrdCompra.setText("N° ORDEN COMPRA");
        jPanelBaseRegGuiaRemision.add(jLabelNumOrdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 260, -1));

        textOrden.setBackground(new java.awt.Color(0, 0, 38));
        textOrden.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textOrden.setForeground(new java.awt.Color(255, 255, 255));
        textOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 40));

        botonArchivo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonArchivo.setText("SUBIR GUÍA REMISIÓN");
        botonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(botonArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 330, 40));

        jLabelProveedor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelProveedor.setForeground(new java.awt.Color(0, 0, 51));
        jLabelProveedor.setText("PROVEEDOR");
        jPanelBaseRegGuiaRemision.add(jLabelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 260, -1));

        textPartida.setBackground(new java.awt.Color(0, 0, 38));
        textPartida.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textPartida.setForeground(new java.awt.Color(255, 255, 255));
        textPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 180, 40));

        jLabelPunPartida.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelPunPartida.setForeground(new java.awt.Color(0, 0, 51));
        jLabelPunPartida.setText("PUNTO PARTIDA");
        jPanelBaseRegGuiaRemision.add(jLabelPunPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, -1));

        jLabelNombreArchivo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNombreArchivo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNombreArchivo.setText("NOMBRE:");
        jPanelBaseRegGuiaRemision.add(jLabelNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 88, 80, 30));

        textNumero.setBackground(new java.awt.Color(0, 0, 38));
        textNumero.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textNumero.setForeground(new java.awt.Color(255, 255, 255));
        textNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 180, 40));

        jLabelMotTraslado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelMotTraslado.setForeground(new java.awt.Color(0, 0, 51));
        jLabelMotTraslado.setText("MOTIVO TRASLADO");
        jPanelBaseRegGuiaRemision.add(jLabelMotTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, -1));

        textProveedor.setBackground(new java.awt.Color(0, 0, 38));
        textProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textProveedor.setForeground(new java.awt.Color(255, 255, 255));
        textProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 40));

        jLabelFechaIniTraslado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelFechaIniTraslado.setForeground(new java.awt.Color(0, 0, 51));
        jLabelFechaIniTraslado.setText("FECHA INICIO TRASLADO");
        jPanelBaseRegGuiaRemision.add(jLabelFechaIniTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 240, -1));

        textAnio.setBackground(new java.awt.Color(0, 0, 38));
        textAnio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textAnio.setForeground(new java.awt.Color(255, 255, 255));
        textAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 50, 40));

        botonBuscar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonBuscar.setText("BUSCAR");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 40));

        javax.swing.GroupLayout panelArchivoLayout = new javax.swing.GroupLayout(panelArchivo);
        panelArchivo.setLayout(panelArchivoLayout);
        panelArchivoLayout.setHorizontalGroup(
            panelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        panelArchivoLayout.setVerticalGroup(
            panelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanelBaseRegGuiaRemision.add(panelArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 330, 240));

        botonGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 110, 40));

        textArchivo.setEditable(false);
        textArchivo.setBackground(new java.awt.Color(0, 0, 38));
        textArchivo.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        textArchivo.setForeground(new java.awt.Color(255, 255, 255));
        textArchivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textArchivo.setBorder(null);
        textArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textArchivoActionPerformed(evt);
            }
        });
        jPanelBaseRegGuiaRemision.add(textArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 240, 40));

        jLabelNumGuiaRemision.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNumGuiaRemision.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNumGuiaRemision.setText("N° GUÍA REMISIÓN");
        jPanelBaseRegGuiaRemision.add(jLabelNumGuiaRemision, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 190, -1));

        textMotivo.setBackground(new java.awt.Color(0, 0, 38));
        textMotivo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textMotivo.setForeground(new java.awt.Color(255, 255, 255));
        textMotivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 320, 40));

        textDia.setBackground(new java.awt.Color(0, 0, 38));
        textDia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textDia.setForeground(new java.awt.Color(255, 255, 255));
        textDia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 50, 40));

        textMes.setBackground(new java.awt.Color(0, 0, 38));
        textMes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textMes.setForeground(new java.awt.Color(255, 255, 255));
        textMes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegGuiaRemision.add(textMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseRegGuiaRemision, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseRegGuiaRemision, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRetPrincipal5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRetPrincipal5MouseClicked
        FrmPrincipal ret5 = new FrmPrincipal();
        ret5.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelRetPrincipal5MouseClicked

    private void botonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoActionPerformed
        
    }//GEN-LAST:event_botonArchivoActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarGuiaRemision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonArchivo;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabelFechaIniTraslado;
    private javax.swing.JLabel jLabelMotTraslado;
    private javax.swing.JLabel jLabelNombreArchivo;
    private javax.swing.JLabel jLabelNumGuiaRemision;
    private javax.swing.JLabel jLabelNumOrdCompra;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelPunPartida;
    private javax.swing.JLabel jLabelRegGuiaRemision;
    private javax.swing.JPanel jPanelBaseRegGuiaRemision;
    private javax.swing.JPanel jPanelRetPrincipal5;
    public javax.swing.JPanel panelArchivo;
    public javax.swing.JTextField textAnio;
    public javax.swing.JTextField textArchivo;
    public javax.swing.JTextField textDia;
    public javax.swing.JTextField textMes;
    public javax.swing.JTextField textMotivo;
    public javax.swing.JTextField textNumero;
    public javax.swing.JTextField textOrden;
    public javax.swing.JTextField textPartida;
    public javax.swing.JTextField textProveedor;
    // End of variables declaration//GEN-END:variables
}
