/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class FrmRegistrarDatosProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarDatosProducto
     */
    public FrmRegistrarDatosProducto() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBaseRegDatosProducto = new javax.swing.JPanel();
        jPanelRetPrincipal3 = new javax.swing.JPanel();
        jLabelReturn = new javax.swing.JLabel();
        jLabelRegDatProducto = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldBlister = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelPrecioVenta = new javax.swing.JLabel();
        jTextFieldPrecioVentaCaja = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jButtonGuardarDatMedicamento = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonModificarDatProducto = new javax.swing.JButton();
        jLabelCodigo1 = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNumBlister = new javax.swing.JTextField();
        jLabelCodigo2 = new javax.swing.JLabel();
        jTextFieldPrecioVentaBlister = new javax.swing.JTextField();
        jLabelPrecioVenta1 = new javax.swing.JLabel();
        jLabelCodigo3 = new javax.swing.JLabel();
        jTextFieldCodigoBlister = new javax.swing.JTextField();
        jLabelCodigo4 = new javax.swing.JLabel();
        jTextFieldCodigoCaja = new javax.swing.JTextField();
        jTextFieldCaja = new javax.swing.JTextField();
        jPanelLinea1 = new javax.swing.JPanel();
        jPanelLinea2 = new javax.swing.JPanel();
        jPanelLinea3 = new javax.swing.JPanel();
        jPanelFranjaDerecha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaseRegDatosProducto.setBackground(new java.awt.Color(239, 248, 255));
        jPanelBaseRegDatosProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRetPrincipal3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRetPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRetPrincipal3MouseClicked(evt);
            }
        });

        jLabelReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRetPrincipal3Layout = new javax.swing.GroupLayout(jPanelRetPrincipal3);
        jPanelRetPrincipal3.setLayout(jPanelRetPrincipal3Layout);
        jPanelRetPrincipal3Layout.setHorizontalGroup(
            jPanelRetPrincipal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        jPanelRetPrincipal3Layout.setVerticalGroup(
            jPanelRetPrincipal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRetPrincipal3Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabelReturn))
        );

        jPanelBaseRegDatosProducto.add(jPanelRetPrincipal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 55, 50));

        jLabelRegDatProducto.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelRegDatProducto.setForeground(new java.awt.Color(0, 0, 51));
        jLabelRegDatProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegDatProducto.setText("REGISTRAR DATOS DEL PRODUCTO");
        jPanelBaseRegDatosProducto.add(jLabelRegDatProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 490, 50));

        jLabelCodigo.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCodigo.setText("CÓDIGO: ");
        jPanelBaseRegDatosProducto.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 90, 20));

        jTextFieldBlister.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldBlister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldBlister.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBlister.setText("Blister");
        jTextFieldBlister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldBlister.setEnabled(false);
        jPanelBaseRegDatosProducto.add(jTextFieldBlister, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 240, 40));

        jLabelNombre.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNombre.setText("NOMBRE:");
        jPanelBaseRegDatosProducto.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 20));

        jTextFieldNombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegDatosProducto.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 240, 40));

        jLabelPeso.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(0, 0, 51));
        jLabelPeso.setText("PESO:");
        jPanelBaseRegDatosProducto.add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 90, 20));

        jTextFieldPeso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPeso.setBorder(null);
        jTextFieldPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegDatosProducto.add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 120, 40));

        jLabelPrecioVenta.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelPrecioVenta.setForeground(new java.awt.Color(0, 0, 51));
        jLabelPrecioVenta.setText("PRECIO VENTA:");
        jPanelBaseRegDatosProducto.add(jLabelPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 150, 20));

        jTextFieldPrecioVentaCaja.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldPrecioVentaCaja.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldPrecioVentaCaja.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecioVentaCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPrecioVentaCaja.setEnabled(false);
        jPanelBaseRegDatosProducto.add(jTextFieldPrecioVentaCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 170, 40));

        jLabelMarca.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(0, 0, 51));
        jLabelMarca.setText("FABRICANTE:");
        jPanelBaseRegDatosProducto.add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 140, 20));

        jButtonGuardarDatMedicamento.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonGuardarDatMedicamento.setText("GUARDAR");
        jPanelBaseRegDatosProducto.add(jButtonGuardarDatMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 120, 40));
        jPanelBaseRegDatosProducto.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 790, 10));

        jButtonModificarDatProducto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonModificarDatProducto.setText("GUARDAR");
        jButtonModificarDatProducto.setEnabled(false);
        jPanelBaseRegDatosProducto.add(jButtonModificarDatProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 120, 40));

        jLabelCodigo1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelCodigo1.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCodigo1.setText("TIPO: ");
        jPanelBaseRegDatosProducto.add(jLabelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 90, 20));

        jComboBoxMarca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBoxMarca.setBorder(null);
        jPanelBaseRegDatosProducto.add(jComboBoxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 290, 40));

        jTextFieldNumBlister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldNumBlister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNumBlister.setBorder(null);
        jTextFieldNumBlister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelBaseRegDatosProducto.add(jTextFieldNumBlister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 40));

        jLabelCodigo2.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelCodigo2.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCodigo2.setText("NUMERO DE BLISTER:");
        jPanelBaseRegDatosProducto.add(jLabelCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 220, 20));

        jTextFieldPrecioVentaBlister.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldPrecioVentaBlister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldPrecioVentaBlister.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecioVentaBlister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPrecioVentaBlister.setEnabled(false);
        jPanelBaseRegDatosProducto.add(jTextFieldPrecioVentaBlister, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 170, 40));

        jLabelPrecioVenta1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelPrecioVenta1.setForeground(new java.awt.Color(0, 0, 51));
        jLabelPrecioVenta1.setText("PRECIO VENTA:");
        jPanelBaseRegDatosProducto.add(jLabelPrecioVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 150, 20));

        jLabelCodigo3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelCodigo3.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCodigo3.setText("TIPO: ");
        jPanelBaseRegDatosProducto.add(jLabelCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 90, 20));

        jTextFieldCodigoBlister.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldCodigoBlister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldCodigoBlister.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoBlister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCodigoBlister.setEnabled(false);
        jPanelBaseRegDatosProducto.add(jTextFieldCodigoBlister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 240, 40));

        jLabelCodigo4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelCodigo4.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCodigo4.setText("CÓDIGO: ");
        jPanelBaseRegDatosProducto.add(jLabelCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 90, 20));

        jTextFieldCodigoCaja.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldCodigoCaja.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldCodigoCaja.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCodigoCaja.setEnabled(false);
        jPanelBaseRegDatosProducto.add(jTextFieldCodigoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 240, 40));

        jTextFieldCaja.setBackground(new java.awt.Color(0, 0, 38));
        jTextFieldCaja.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldCaja.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCaja.setText("Caja");
        jTextFieldCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCaja.setEnabled(false);
        jTextFieldCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCajaActionPerformed(evt);
            }
        });
        jPanelBaseRegDatosProducto.add(jTextFieldCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 240, 40));

        jPanelLinea1.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea1Layout = new javax.swing.GroupLayout(jPanelLinea1);
        jPanelLinea1.setLayout(jPanelLinea1Layout);
        jPanelLinea1Layout.setHorizontalGroup(
            jPanelLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanelLinea1Layout.setVerticalGroup(
            jPanelLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBaseRegDatosProducto.add(jPanelLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, 3));

        jPanelLinea2.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea2Layout = new javax.swing.GroupLayout(jPanelLinea2);
        jPanelLinea2.setLayout(jPanelLinea2Layout);
        jPanelLinea2Layout.setHorizontalGroup(
            jPanelLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanelLinea2Layout.setVerticalGroup(
            jPanelLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBaseRegDatosProducto.add(jPanelLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 120, 3));

        jPanelLinea3.setBackground(new java.awt.Color(0, 5, 25));

        javax.swing.GroupLayout jPanelLinea3Layout = new javax.swing.GroupLayout(jPanelLinea3);
        jPanelLinea3.setLayout(jPanelLinea3Layout);
        jPanelLinea3Layout.setHorizontalGroup(
            jPanelLinea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanelLinea3Layout.setVerticalGroup(
            jPanelLinea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBaseRegDatosProducto.add(jPanelLinea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 240, 3));

        jPanelFranjaDerecha.setBackground(new java.awt.Color(23, 178, 178));

        javax.swing.GroupLayout jPanelFranjaDerechaLayout = new javax.swing.GroupLayout(jPanelFranjaDerecha);
        jPanelFranjaDerecha.setLayout(jPanelFranjaDerechaLayout);
        jPanelFranjaDerechaLayout.setHorizontalGroup(
            jPanelFranjaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelFranjaDerechaLayout.setVerticalGroup(
            jPanelFranjaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelBaseRegDatosProducto.add(jPanelFranjaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 65, 60, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseRegDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseRegDatosProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRetPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRetPrincipal3MouseClicked
//        FrmPrincipal ret3 = new FrmPrincipal();
//        ret3.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jPanelRetPrincipal3MouseClicked

    private void jTextFieldCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarDatosProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGuardarDatMedicamento;
    public javax.swing.JButton jButtonModificarDatProducto;
    public javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelCodigo3;
    private javax.swing.JLabel jLabelCodigo4;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPrecioVenta;
    private javax.swing.JLabel jLabelPrecioVenta1;
    private javax.swing.JLabel jLabelRegDatProducto;
    private javax.swing.JLabel jLabelReturn;
    private javax.swing.JPanel jPanelBaseRegDatosProducto;
    private javax.swing.JPanel jPanelFranjaDerecha;
    private javax.swing.JPanel jPanelLinea1;
    private javax.swing.JPanel jPanelLinea2;
    private javax.swing.JPanel jPanelLinea3;
    public javax.swing.JPanel jPanelRetPrincipal3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextFieldBlister;
    public javax.swing.JTextField jTextFieldCaja;
    public javax.swing.JTextField jTextFieldCodigoBlister;
    public javax.swing.JTextField jTextFieldCodigoCaja;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldNumBlister;
    public javax.swing.JTextField jTextFieldPeso;
    public javax.swing.JTextField jTextFieldPrecioVentaBlister;
    public javax.swing.JTextField jTextFieldPrecioVentaCaja;
    // End of variables declaration//GEN-END:variables
}
